### ISSUE TITLE
Can't run Container 

### ISSUE THREAD

**Issue by magdalenatsolaki** [teid/postfix-ldap#1]
Hello,
I got this message:

docker run -d -p 25:25 --link ldap-container:ldap --link mda-container:mda -e LDAP_USER_FIELD="uid" -e LDAP_BASE="ou=users,dc=yourdomain,dc=com" -e DOMAIN="yourdomain.com" -e HOSTNAME="smtp.yourdomain.com" teid/postfix-ldap

docker: Error response from daemon: Could not get container for ldap-container.
See 'docker run --help'.

Thanks

**Comment by teid** [comment]
Hi, 

This container needs other containers to run:
* A ldap server to authenticate the users
* A mail delivery agent  (MDA) to deliver the mails using the LMTP protocol (you can check https://github.com/teid/dovecot-ldap)

In this example I was using the docker link feature to bind the postfix-ldap container to its dependencies.

The error message is telling you that there is no container named `ldap-container`. You should create one and update the `--link` option to match the name
